name: PR Information

on:
  pull_request:
    types: [opened]

jobs:
  print-pr-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR information
        run: |
          echo "Pull Request Title: ${{ github.event.pull_request.title }}"
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
