name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set URL for Stage
        run: |
          # Set URL with stage name as an environment variable
          echo "STAGE_URL=https://example.com/stage" >> $GITHUB_ENV
      - name: Display URL for Stage
        run: |
          # Retrieve URL from environment variable and display it
          # echo "URL for Stage: $STAGE_URL"
          # echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
          #- name: Display URL for Stage
          # Retrieve URL from environment variable and display it
          PR_URL="pr-${{ github.event.pull_request.number }}.example.com"
          echo "### Deployment is Successful and Now can access app with subdomain [${PR_URL}](http://${PR_URL}) :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "### Note: URL will be accessible after 5 mint from deployment" >> $GITHUB_STEP_SUMMARY
