name: Display Details After Job Finish

on:
  workflow_run:
    workflows: ["test"] # Replace with the name of your workflow
    types:
      - completed

jobs:
  display_details:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Job Finish Details
        run: |
          echo "Job finished successfully!"
          echo "Additional details here."
